// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine.h"
#include "Net/UnrealNetwork.h"

class UBehaviorTreeComponent;

DECLARE_LOG_CATEGORY_EXTERN(LogShooter, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogShooterWeapon, Log, All);

#define COLLISION_WEAPON ECC_GameTraceChannel1
#define COLLISION_PROJECTILE ECC_GameTraceChannel2
#define COLLISION_PICKUP ECC_GameTraceChannel3

#define MAX_PLAYER_NAME_LENGTH 16


#ifndef SHOOTER_CONSOLE_UI
	#define SHOOTER_SIMULATE_CONSOLE_UI 0
	#if  PLATFORM_SWITCH || SHOOTER_SIMULATE_CONSOLE_UI
		#define SHOOTER_CONSOLE_UI 1
	#else
		#define SHOOTER_CONSOLE_UI 0
	#endif
#endif

#ifndef SHOOTER_XBOX_STRINGS
	#define  SHOOTER_XBOX_STRINGS 0
#endif

#ifndef SHOOTER_SHOW_QUIT_MENU_ITEM
	#define SHOOTER_SHOW_QUIT_MENU_ITEM (!SHOOTER_CONSOLE_UI)
#endif

#ifndef SHOOTER_SUPPORTS_OFFLINE_SPLIT_SCREEN
	#define SHOOTER_SUPPORTS_OFFLINE_SPLIT_SCREEN 1
#endif

#ifndef SHOOTER_CONTROLLER_PAIRING_ON_DISCONNECT
#define SHOOTER_CONTROLLER_PAIRING_ON_DISCONNECT 1
#endif

#ifndef  SHOOTER_CONTROLLER_PAIRING_PROMPT_FOR_NEW_USER_WHEN_RECONNECTING
#define SHOOTER_CONTROLLER_PAIRING_PROMPT_FOR_NEW_USER_WHEN_RECONNECTING 0
#endif


